// <auto-generated />
using Caiman.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caiman.Migrations
{
    [DbContext(typeof(CaimanContext))]
    partial class CaimanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Caiman.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Caiman.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Caiman.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Caiman.Models.LargeCategory", b =>
                {
                    b.HasBaseType("Caiman.Models.Category");

                    b.HasDiscriminator().HasValue("LargeCategory");
                });

            modelBuilder.Entity("Caiman.Models.MediumCategory", b =>
                {
                    b.HasBaseType("Caiman.Models.Category");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("MediumCategory");
                });

            modelBuilder.Entity("Caiman.Models.SmallCategory", b =>
                {
                    b.HasBaseType("Caiman.Models.Category");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ParentId");

                    b.ToTable("Category", t =>
                        {
                            t.Property("ParentId")
                                .HasColumnName("SmallCategory_ParentId");
                        });

                    b.HasDiscriminator().HasValue("SmallCategory");
                });

            modelBuilder.Entity("Caiman.Models.Item", b =>
                {
                    b.HasOne("Caiman.Models.SmallCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caiman.Models.Place", "Place")
                        .WithMany("Items")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Caiman.Models.MediumCategory", b =>
                {
                    b.HasOne("Caiman.Models.LargeCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Caiman.Models.SmallCategory", b =>
                {
                    b.HasOne("Caiman.Models.MediumCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Caiman.Models.Place", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Caiman.Models.LargeCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Caiman.Models.MediumCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Caiman.Models.SmallCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
