name: Execute Buffalo test
on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - Caiman/**
      - Cougar/**
      - Buffalo/**
      - .github/workflows/test.yml

  pull_request:
    branches:
      - master

  check_run:
    types:
      - created

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build Buffalo and test it
    runs-on: windows-latest

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0'

      - name: Setup Ollama
        uses: ai-action/setup-ollama@v2

      - name: Pull Gemma4 E2B
        run: ollama pull gemma4:e2b

      - name: Conduct test
        run: dotnet test Buffalo/Buffalo.csproj -a x64 -c Debug -p:Platform=x64
